// <auto-generated />
using System;
using FitnessPlatform;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessPlatform.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20260726045209_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessPlatform.Models.BodyMeasurement", b =>
                {
                    b.Property<int>("measurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("measurementId"));

                    b.Property<double?>("armCircumference")
                        .HasColumnType("float");

                    b.Property<double>("bodyFatPercentage")
                        .HasColumnType("float");

                    b.Property<double?>("chestCircumference")
                        .HasColumnType("float");

                    b.Property<double?>("hipCircumference")
                        .HasColumnType("float");

                    b.Property<DateTime>("measurementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("thighCircumference")
                        .HasColumnType("float");

                    b.Property<double>("waistCircumference")
                        .HasColumnType("float");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.HasKey("measurementId");

                    b.HasIndex("memberId");

                    b.ToTable("BodyMeasurements");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Exercise", b =>
                {
                    b.Property<int>("exerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("exerciseId"));

                    b.Property<string>("difficulityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("equipment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("exerciseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("targetMuscle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("videoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("exerciseId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Member", b =>
                {
                    b.Property<int>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("memberId"));

                    b.Property<double>("currentWeight")
                        .HasColumnType("float");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("height")
                        .HasColumnType("float");

                    b.Property<DateTime>("joinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("memberId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("FitnessPlatform.Models.MembershipPlan", b =>
                {
                    b.Property<int>("planId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("planId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("durationInDays")
                        .HasColumnType("int");

                    b.Property<string>("planName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("planId");

                    b.ToTable("MembershipPlans");
                });

            modelBuilder.Entity("FitnessPlatform.Models.NutritionPlan", b =>
                {
                    b.Property<int>("nutritionPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nutritionPlanId"));

                    b.Property<int>("carbsGrams")
                        .HasColumnType("int");

                    b.Property<int>("dailyCalories")
                        .HasColumnType("int");

                    b.Property<int>("fatGrams")
                        .HasColumnType("int");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("planName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("proteinGrams")
                        .HasColumnType("int");

                    b.Property<int>("trainerId")
                        .HasColumnType("int");

                    b.HasKey("nutritionPlanId");

                    b.HasIndex("memberId");

                    b.HasIndex("trainerId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("FitnessPlatform.Models.ProgramExercise", b =>
                {
                    b.Property<int>("programExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("programExerciseId"));

                    b.Property<string>("dayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("exerciseId")
                        .HasColumnType("int");

                    b.Property<int>("programId")
                        .HasColumnType("int");

                    b.Property<int>("repetitions")
                        .HasColumnType("int");

                    b.Property<int>("restTime")
                        .HasColumnType("int");

                    b.Property<int>("sets")
                        .HasColumnType("int");

                    b.HasKey("programExerciseId");

                    b.HasIndex("exerciseId");

                    b.HasIndex("programId");

                    b.ToTable("ProgramExercises");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Subscription", b =>
                {
                    b.Property<int>("subscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("subscriptionId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<int>("planId")
                        .HasColumnType("int");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("subscriptionId");

                    b.HasIndex("memberId");

                    b.HasIndex("planId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Trainer", b =>
                {
                    b.Property<int>("traninerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("traninerId"));

                    b.Property<string>("certification")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("yearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("traninerId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("FitnessPlatform.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessPlatform.Models.WorkoutProgram", b =>
                {
                    b.Property<int>("programId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("programId"));

                    b.Property<int>("DurationInWeeks")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<string>("programName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("trainerId")
                        .HasColumnType("int");

                    b.HasKey("programId");

                    b.HasIndex("memberId");

                    b.HasIndex("trainerId");

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("FitnessPlatform.Models.WorkoutSession", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionId"));

                    b.Property<int>("caloriesBurned")
                        .HasColumnType("int");

                    b.Property<int>("durationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("isCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("memberId")
                        .HasColumnType("int");

                    b.Property<int>("programId")
                        .HasColumnType("int");

                    b.Property<DateTime>("sessionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("sessionId");

                    b.HasIndex("memberId");

                    b.HasIndex("programId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessPlatform.Models.BodyMeasurement", b =>
                {
                    b.HasOne("FitnessPlatform.Models.Member", "Member")
                        .WithMany("BodyMeasurements")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Member", b =>
                {
                    b.HasOne("FitnessPlatform.Models.User", "User")
                        .WithOne("Member")
                        .HasForeignKey("FitnessPlatform.Models.Member", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPlatform.Models.NutritionPlan", b =>
                {
                    b.HasOne("FitnessPlatform.Models.Member", "Member")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessPlatform.Models.Trainer", "Trainer")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("trainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessPlatform.Models.ProgramExercise", b =>
                {
                    b.HasOne("FitnessPlatform.Models.Exercise", "Exercise")
                        .WithMany("ProgramExercises")
                        .HasForeignKey("exerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessPlatform.Models.WorkoutProgram", "WorkoutProgram")
                        .WithMany("ProgramExercises")
                        .HasForeignKey("programId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Subscription", b =>
                {
                    b.HasOne("FitnessPlatform.Models.Member", "Member")
                        .WithMany("Subscriptions")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessPlatform.Models.MembershipPlan", "MembershipPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("planId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Trainer", b =>
                {
                    b.HasOne("FitnessPlatform.Models.User", "User")
                        .WithOne("Trainer")
                        .HasForeignKey("FitnessPlatform.Models.Trainer", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessPlatform.Models.WorkoutProgram", b =>
                {
                    b.HasOne("FitnessPlatform.Models.Member", "Member")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessPlatform.Models.Trainer", "Trainer")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("trainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessPlatform.Models.WorkoutSession", b =>
                {
                    b.HasOne("FitnessPlatform.Models.Member", "Member")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("memberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessPlatform.Models.WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("programId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Exercise", b =>
                {
                    b.Navigation("ProgramExercises");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Member", b =>
                {
                    b.Navigation("BodyMeasurements");

                    b.Navigation("NutritionPlans");

                    b.Navigation("Subscriptions");

                    b.Navigation("WorkoutPrograms");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessPlatform.Models.MembershipPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FitnessPlatform.Models.Trainer", b =>
                {
                    b.Navigation("NutritionPlans");

                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("FitnessPlatform.Models.User", b =>
                {
                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("FitnessPlatform.Models.WorkoutProgram", b =>
                {
                    b.Navigation("ProgramExercises");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
